version: '3'

services:
  db:
    container_name: postgres_db_users
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - users_data:/var/lib/postgresql/data

  api:
    container_name: spring_api_users
    build:
      context: .
      dockerfile: Dockerfile.multi
    ports:
      - 8080:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: postgres
      DB_HOST: postgres_db_users
      DB_PORT: 5432
      JJ_SECRET: secret_key
      JJ_EXPIRATION: 1000000000

volumes:
  users_data: