server:
  error:
    include-message: always
  servlet:
    context-path: /api/user
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

JJ_SECRET: secret_key
JJ_EXPIRATION: 1000000000
